from __future__ import annotations

import csv
import json
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from origin_ai_lab.connectors.software_discovery import discover_comsol
from origin_ai_lab.models import ThermalSimulationSpec
from origin_ai_lab.simulations.vv import parse_comsol_solver_log


class ComsolUnavailable(RuntimeError):
    """Raised when COMSOL execution is requested but no local bridge is configured."""

    def __init__(self, message: str, details: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.details = details or {}


COMSOL_BATCH_TIMEOUT_SECONDS = 1800


class ComsolThermalClient:
    """Boundary for COMSOL thermal template execution and result export.

    The connector uses two guarded boundaries:

    1. Solve an existing, validated MPH template with ``comsolbatch``.
    2. Run a fixed Java post-processing helper generated by this module.

    The Java helper is intentionally not a free-form script surface. It only
    loads the solved model and attempts a small approved export set: max
    temperature, temperature data CSV, and an image from an existing plot group.
    Future template-specific methods should be added as reviewed templates or
    model methods, not as LLM-generated COMSOL code.
    """

    def __init__(self, executable_path: Path | None = None) -> None:
        self.executable_path = executable_path

    def run_thermal_study(self, spec: ThermalSimulationSpec, output_dir: Path) -> dict[str, Any]:
        if spec.template_path is None:
            raise ComsolUnavailable("COMSOL backend requires an existing .mph template path.")
        template_path = spec.template_path.resolve()
        if not template_path.exists():
            raise ComsolUnavailable(f"COMSOL template does not exist: {template_path}")

        executable_path = self.executable_path or _default_comsolbatch_path()
        output_dir.mkdir(parents=True, exist_ok=True)
        output_mph = output_dir / f"{template_path.stem}_solved.mph"
        batch_log = output_dir / f"{template_path.stem}_comsolbatch.log"
        status_file = output_dir / f"{template_path.stem}_solved.mph.status"

        command = [
            str(executable_path),
            "-inputfile",
            str(template_path),
            "-outputfile",
            str(output_mph),
            "-batchlog",
            str(batch_log),
        ]
        if spec.study_type and spec.study_type.lower().startswith("std"):
            command.extend(["-study", spec.study_type])

        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=COMSOL_BATCH_TIMEOUT_SECONDS,
        )
        log_text = _read_text_lossy(batch_log)
        artifacts = {
            "output_mph": str(output_mph),
            "batch_log": str(batch_log),
        }
        if status_file.exists():
            artifacts["status_file"] = str(status_file)

        solver_log_summary = parse_comsol_solver_log(log_text, completed.returncode)
        failure_details = {
            "solver": "comsolbatch",
            "solver_converged": solver_log_summary.completed,
            "return_code": completed.returncode,
            "command": command,
            "batch_log": str(batch_log),
            "status_file": str(status_file) if status_file.exists() else None,
            "log_summary": solver_log_summary.to_dict(),
            "solver_log_summary": solver_log_summary.to_dict(),
            "artifacts": artifacts,
        }
        if completed.returncode != 0:
            _write_result_manifest(
                output_dir=output_dir,
                template_path=template_path,
                status="solve_failed",
                solve_command=command,
                solve_return_code=completed.returncode,
                artifacts=artifacts,
                log_summary=_summarize_log(log_text),
                exports=[],
                compile_command=None,
                compile_return_code=None,
                compile_log_summary=None,
                export_command=None,
                export_return_code=None,
                missing=["solved_mph", "temperature_field_png", "temperature_table_csv", "max_temperature_csv"],
            )
            raise ComsolUnavailable(
                "COMSOL batch execution failed with exit code "
                f"{completed.returncode}. See {batch_log}.",
                details=failure_details,
            )
        if not output_mph.exists():
            _write_result_manifest(
                output_dir=output_dir,
                template_path=template_path,
                status="solve_missing_output",
                solve_command=command,
                solve_return_code=completed.returncode,
                artifacts=artifacts,
                log_summary=_summarize_log(log_text),
                exports=[],
                compile_command=None,
                compile_return_code=None,
                compile_log_summary=None,
                export_command=None,
                export_return_code=None,
                missing=["solved_mph", "temperature_field_png", "temperature_table_csv", "max_temperature_csv"],
            )
            raise ComsolUnavailable(
                f"COMSOL batch completed but did not create {output_mph}.",
                details=failure_details,
            )

        export_result = _run_controlled_result_export(
            executable_path=executable_path,
            solved_mph=output_mph,
            output_dir=output_dir,
            template_stem=template_path.stem,
        )
        artifacts.update(export_result["artifacts"])
        missing = [
            export["id"]
            for export in export_result["exports"]
            if export.get("status") not in {"created", "available"}
        ]
        result_manifest = _write_result_manifest(
            output_dir=output_dir,
            template_path=template_path,
            status="complete" if not missing else "partial",
            solve_command=command,
            solve_return_code=completed.returncode,
            artifacts=artifacts,
            log_summary=_summarize_log(log_text),
            exports=export_result["exports"],
            compile_command=export_result["compile_command"],
            compile_return_code=export_result["compile_return_code"],
            compile_log_summary=export_result["compile_log_summary"],
            export_command=export_result["command"],
            export_return_code=export_result["return_code"],
            missing=missing,
        )
        artifacts["result_manifest"] = str(result_manifest)

        metrics: dict[str, Any] = {
            "solver": "comsolbatch",
            "solver_converged": solver_log_summary.completed,
            "return_code": completed.returncode,
            "command": command,
            "output_mph": str(output_mph),
            "batch_log": str(batch_log),
            "status_file": str(status_file) if status_file.exists() else None,
            "result_manifest": str(result_manifest),
            "log_summary": solver_log_summary.to_dict(),
            "solver_log_summary": solver_log_summary.to_dict(),
            "exports": export_result["exports"],
            "export_compile_command": export_result["compile_command"],
            "export_compile_return_code": export_result["compile_return_code"],
            "export_compile_log_summary": export_result["compile_log_summary"],
            "export_command": export_result["command"],
            "export_return_code": export_result["return_code"],
            "export_log_summary": export_result["log_summary"],
            "export_security_note": export_result["security_note"],
            "artifacts": artifacts,
            "parameter_updates_applied": False,
            "parameter_update_note": (
                "This smoke-test connector solves an existing MPH template. "
                "Parameter mutation will be enabled through reviewed COMSOL template methods."
            ),
        }
        metrics.update(export_result["metrics"])
        return metrics


def _default_comsolbatch_path() -> Path:
    install = discover_comsol()
    if not install.found or install.executable_path is None:
        raise ComsolUnavailable("COMSOL batch executable was not found. Run `origin-ai doctor` for details.")
    executable_path = install.executable_path
    if executable_path.name.lower() == "comsol.exe":
        sibling_batch = executable_path.with_name("comsolbatch.exe")
        if sibling_batch.exists():
            return sibling_batch
    return executable_path


def _default_comsolcompile_path(batch_executable_path: Path) -> Path:
    compile_name = "comsolcompile.exe" if batch_executable_path.suffix.lower() == ".exe" else "comsolcompile"
    sibling_compile = batch_executable_path.with_name(compile_name)
    return sibling_compile if sibling_compile.exists() else Path(compile_name)


def _run_controlled_result_export(
    executable_path: Path,
    solved_mph: Path,
    output_dir: Path,
    template_stem: str,
) -> dict[str, Any]:
    """Run the fixed COMSOL Java result export helper.

    Export failures are recorded as partial evidence rather than treated as a
    failed solve. This keeps the batch solve useful while making missing result
    evidence explicit in the manifest.
    """

    export_java = output_dir / "ComsolResultExport.java"
    export_class = output_dir / "ComsolResultExport.class"
    compile_log = output_dir / f"{template_stem}_result_export_compile.log"
    export_log = output_dir / f"{template_stem}_result_export.log"
    postprocessed_mph = output_dir / f"{template_stem}_postprocessed.mph"
    temperature_png = output_dir / f"{template_stem}_temperature_field.png"
    temperature_table_csv = output_dir / f"{template_stem}_temperature_table.csv"
    max_temperature_csv = output_dir / f"{template_stem}_max_temperature.csv"
    export_status = output_dir / f"{template_stem}_export_status.tsv"

    with tempfile.TemporaryDirectory(prefix="origin-ai-comsol-") as raw_stage_dir:
        stage_dir = Path(raw_stage_dir)
        stage_solved_mph = stage_dir / solved_mph.name
        stage_java = stage_dir / "ComsolResultExport.java"
        stage_class = stage_dir / "ComsolResultExport.class"
        stage_postprocessed_mph = stage_dir / postprocessed_mph.name
        stage_temperature_png = stage_dir / temperature_png.name
        stage_temperature_table_csv = stage_dir / temperature_table_csv.name
        stage_max_temperature_csv = stage_dir / max_temperature_csv.name
        stage_export_status = stage_dir / export_status.name
        stage_prefs_dir = stage_dir / "prefs"

        shutil.copy2(solved_mph, stage_solved_mph)
        _write_comsol_security_prefs(stage_prefs_dir)
        stage_java.write_text(
            _controlled_export_java(
                solved_mph=stage_solved_mph,
                output_dir=stage_dir,
                temperature_png=stage_temperature_png,
                temperature_table_csv=stage_temperature_table_csv,
                max_temperature_csv=stage_max_temperature_csv,
                export_status=stage_export_status,
            ),
            encoding="utf-8",
        )
        shutil.copy2(stage_java, export_java)

        compile_command = [str(_default_comsolcompile_path(executable_path)), str(stage_java)]
        try:
            compile_completed = subprocess.run(
                compile_command,
                check=False,
                capture_output=True,
                text=True,
                timeout=COMSOL_BATCH_TIMEOUT_SECONDS,
            )
            compile_return_code: int | None = compile_completed.returncode
            _write_process_log(compile_log, compile_completed.stdout, compile_completed.stderr)
        except Exception as exc:
            compile_return_code = None
            compile_log.write_text(
                f"COMSOL controlled result export compile failed before launch: {exc}\n",
                encoding="utf-8",
            )

        _copy_existing_files({stage_class: export_class})
        if compile_return_code != 0 or not stage_class.exists():
            return {
                "compile_command": compile_command,
                "compile_return_code": compile_return_code,
                "compile_log_summary": _summarize_log(_read_text_lossy(compile_log)),
                "command": None,
                "return_code": None,
                "log_summary": _summarize_log(""),
                "security_note": "COMSOL export helper prepared a per-run prefsdir with security.external.filepermission=full.",
                "artifacts": _existing_artifacts(
                    {
                        "export_helper_java": export_java,
                        "export_helper_class": export_class,
                        "export_compile_log": compile_log,
                    }
                ),
                "exports": _missing_export_records(temperature_png, temperature_table_csv, max_temperature_csv),
                "metrics": {},
            }

        command = [
            str(executable_path),
            "-prefsdir",
            str(stage_prefs_dir),
            "-inputfile",
            str(stage_class),
            "-outputfile",
            str(stage_postprocessed_mph),
            "-batchlog",
            str(export_log),
        ]
        try:
            completed = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
                timeout=COMSOL_BATCH_TIMEOUT_SECONDS,
            )
            return_code: int | None = completed.returncode
        except Exception as exc:
            export_log.write_text(f"COMSOL controlled result export failed before launch: {exc}\n", encoding="utf-8")
            return_code = None

        actual_stage_postprocessed = _first_existing_path(
            stage_postprocessed_mph,
            *sorted(stage_dir.glob(f"{stage_postprocessed_mph.stem}*.mph")),
        )
        postprocessed_paths = {actual_stage_postprocessed: postprocessed_mph} if actual_stage_postprocessed else {}
        _copy_existing_files(
            {
                stage_class: export_class,
                stage_temperature_png: temperature_png,
                stage_temperature_table_csv: temperature_table_csv,
                stage_max_temperature_csv: max_temperature_csv,
                stage_export_status: export_status,
                **postprocessed_paths,
            }
        )

    status_rows = _read_export_status(export_status)
    metrics = _parse_max_temperature_csv(max_temperature_csv)
    if not metrics:
        metrics = _derive_max_temperature_from_table(temperature_table_csv, max_temperature_csv)
        if metrics:
            status_rows["max_temperature_csv"] = {
                "id": "max_temperature_csv",
                "status": "created",
                "path": str(max_temperature_csv),
                "message": "computed_from_temperature_table_csv",
            }
    artifacts = _existing_artifacts(
        {
            "export_helper_java": export_java,
            "export_helper_class": export_class,
            "export_compile_log": compile_log,
            "export_log": export_log,
            "postprocessed_mph": postprocessed_mph,
            "temperature_field_png": temperature_png,
            "temperature_table_csv": temperature_table_csv,
            "max_temperature_csv": max_temperature_csv,
            "export_status_tsv": export_status,
        }
    )
    exports = [
        _export_record(
            export_id="temperature_field_png",
            kind="image",
            path=temperature_png,
            expression="T",
            status_rows=status_rows,
            source="controlled_java_export",
        ),
        _export_record(
            export_id="temperature_table_csv",
            kind="csv",
            path=temperature_table_csv,
            expression="T",
            status_rows=status_rows,
            source="controlled_java_export",
        ),
        _export_record(
            export_id="max_temperature_csv",
            kind="csv",
            path=max_temperature_csv,
            expression="T",
            status_rows=status_rows,
            source="controlled_java_export",
        ),
    ]
    return {
        "compile_command": compile_command,
        "compile_return_code": compile_return_code,
        "compile_log_summary": _summarize_log(_read_text_lossy(compile_log)),
        "command": command,
        "return_code": return_code,
        "log_summary": _summarize_log(_read_text_lossy(export_log)),
        "security_note": "COMSOL export helper used a per-run prefsdir with security.external.filepermission=full.",
        "artifacts": artifacts,
        "exports": exports,
        "metrics": metrics,
    }


def _controlled_export_java(
    solved_mph: Path,
    output_dir: Path,
    temperature_png: Path,
    temperature_table_csv: Path,
    max_temperature_csv: Path,
    export_status: Path,
) -> str:
    return f"""import com.comsol.model.*;
import com.comsol.model.util.*;
import java.io.*;

public class ComsolResultExport {{
  public static Model run() {{
    String modelPath = {_java_string(str(solved_mph))};
    String outputDir = {_java_string(str(output_dir))};
    String temperaturePngPath = {_java_string(str(temperature_png))};
    String temperatureTableCsvPath = {_java_string(str(temperature_table_csv))};
    String maxTemperatureCsvPath = {_java_string(str(max_temperature_csv))};
    String exportStatusPath = {_java_string(str(export_status))};

    ensureDirectory(outputDir);
    initializeStatus(exportStatusPath);
    Model model = loadModel(modelPath);
    String dataTag = firstTag(model.result().dataset().tags(), "dset1");
    String plotGroupTag = firstTag(model.result().tags(), "");

    exportMaxTemperature(model, dataTag, maxTemperatureCsvPath, exportStatusPath);
    exportTemperatureData(model, dataTag, temperatureTableCsvPath, exportStatusPath);
    exportTemperatureImage(model, plotGroupTag, temperaturePngPath, exportStatusPath);
    return model;
  }}

  public static void main(String[] args) {{
    run();
  }}

  private static Model loadModel(String modelPath) {{
    try {{
      return ModelUtil.load("Model", modelPath);
    }} catch (IOException error) {{
      throw new RuntimeException(error);
    }}
  }}

  private static void exportMaxTemperature(Model model, String dataTag, String outputPath, String statusPath) {{
    String[] featureTypes = new String[] {{"MaxVolume", "MaxSurface", "MaxLine", "MaxPoint"}};
    Throwable lastError = null;
    for (int i = 0; i < featureTypes.length; i++) {{
      String tag = "oaiMaxT";
      try {{
        removeNumericalIfPresent(model, tag);
        model.result().numerical().create(tag, featureTypes[i]);
        if (dataTag.length() > 0) {{
          model.result().numerical(tag).set("data", dataTag);
        }}
        model.result().numerical(tag).setIndex("expr", "T", 0);
        model.result().numerical(tag).setIndex("unit", "degC", 0);
        double[][] values = model.result().numerical(tag).getReal();
        double maxValue = firstFinite(values);
        writeMetricCsv(outputPath, "max_temperature_C", maxValue, "degC", "T");
        recordStatus(statusPath, "max_temperature_csv", "created", outputPath, featureTypes[i]);
        return;
      }} catch (Throwable error) {{
        lastError = error;
      }}
    }}
    recordStatus(statusPath, "max_temperature_csv", "failed", outputPath, errorMessage(lastError));
  }}

  private static void exportTemperatureData(Model model, String dataTag, String outputPath, String statusPath) {{
    String tag = "oaiDataT";
    try {{
      removeExportIfPresent(model, tag);
      if (dataTag.length() > 0) {{
        model.result().export().create(tag, dataTag, "Data");
        model.result().export(tag).set("data", dataTag);
      }} else {{
        model.result().export().create(tag, "Data");
      }}
      model.result().export(tag).setIndex("expr", "T", 0);
      model.result().export(tag).setIndex("unit", "degC", 0);
      model.result().export(tag).set("filename", outputPath);
      model.result().export(tag).set("header", "on");
      model.result().export(tag).set("ifexists", "overwrite");
      model.result().export(tag).run();
      recordStatus(statusPath, "temperature_table_csv", "created", outputPath, dataTag);
    }} catch (Throwable error) {{
      recordStatus(statusPath, "temperature_table_csv", "failed", outputPath, errorMessage(error));
    }}
  }}

  private static void exportTemperatureImage(Model model, String plotGroupTag, String outputPath, String statusPath) {{
    String tag = "oaiImageT";
    if (plotGroupTag.length() == 0) {{
      recordStatus(statusPath, "temperature_field_png", "skipped", outputPath, "No result plot group was found.");
      return;
    }}
    try {{
      removeExportIfPresent(model, tag);
      model.result().export().create(tag, plotGroupTag, "Image");
      model.result().export(tag).set("plotgroup", plotGroupTag);
      model.result().export(tag).set("target", "file");
      model.result().export(tag).set("imagetype", "png");
      model.result().export(tag).set("pngfilename", outputPath);
      model.result().export(tag).run();
      recordStatus(statusPath, "temperature_field_png", "created", outputPath, plotGroupTag);
    }} catch (Throwable error) {{
      recordStatus(statusPath, "temperature_field_png", "failed", outputPath, errorMessage(error));
    }}
  }}

  private static void removeNumericalIfPresent(Model model, String tag) {{
    try {{
      if (model.result().numerical().hasTag(tag)) {{
        model.result().numerical().remove(tag);
      }}
    }} catch (Throwable ignored) {{
    }}
  }}

  private static void removeExportIfPresent(Model model, String tag) {{
    try {{
      if (model.result().export().hasTag(tag)) {{
        model.result().export().remove(tag);
      }}
    }} catch (Throwable ignored) {{
    }}
  }}

  private static String firstTag(String[] tags, String fallback) {{
    if (tags == null) {{
      return fallback;
    }}
    for (int i = 0; i < tags.length; i++) {{
      if (tags[i] != null && tags[i].length() > 0) {{
        return tags[i];
      }}
    }}
    return fallback;
  }}

  private static double firstFinite(double[][] values) {{
    if (values != null) {{
      for (int i = 0; i < values.length; i++) {{
        if (values[i] == null) {{
          continue;
        }}
        for (int j = 0; j < values[i].length; j++) {{
          double value = values[i][j];
          if (!Double.isNaN(value) && !Double.isInfinite(value)) {{
            return value;
          }}
        }}
      }}
    }}
    throw new RuntimeException("No finite max temperature value was returned.");
  }}

  private static void ensureDirectory(String path) {{
    File directory = new File(path);
    if (!directory.exists()) {{
      directory.mkdirs();
    }}
  }}

  private static void initializeStatus(String path) {{
    try {{
      PrintWriter writer = new PrintWriter(new OutputStreamWriter(new FileOutputStream(path, false), "UTF-8"));
      writer.println("id\\tstatus\\tpath\\tmessage");
      writer.close();
    }} catch (IOException ignored) {{
    }}
  }}

  private static void recordStatus(String path, String id, String status, String artifactPath, String message) {{
    try {{
      PrintWriter writer = new PrintWriter(new OutputStreamWriter(new FileOutputStream(path, true), "UTF-8"));
      writer.println(clean(id) + "\\t" + clean(status) + "\\t" + clean(artifactPath) + "\\t" + clean(message));
      writer.close();
    }} catch (IOException ignored) {{
    }}
  }}

  private static String clean(String value) {{
    if (value == null) {{
      return "";
    }}
    return value.replace("\\t", " ").replace("\\r", " ").replace("\\n", " ");
  }}

  private static String errorMessage(Throwable error) {{
    if (error == null) {{
      return "";
    }}
    return error.getClass().getName() + ": " + error.getMessage();
  }}

  private static void writeMetricCsv(String path, String metric, double value, String unit, String expression) {{
    try {{
      PrintWriter writer = new PrintWriter(new OutputStreamWriter(new FileOutputStream(path, false), "UTF-8"));
      writer.println("metric,value,unit,expression");
      writer.println(csv(metric) + "," + Double.toString(value) + "," + csv(unit) + "," + csv(expression));
      writer.close();
    }} catch (IOException error) {{
      throw new RuntimeException(error);
    }}
  }}

  private static String csv(String value) {{
    if (value == null) {{
      return "";
    }}
    String escaped = value.replace("\\\"", "\\\"\\\"");
    if (escaped.indexOf(',') >= 0 || escaped.indexOf('"') >= 0 || escaped.indexOf('\\n') >= 0) {{
      return "\\\"" + escaped + "\\\"";
    }}
    return escaped;
  }}
}}
"""


def _write_result_manifest(
    output_dir: Path,
    template_path: Path,
    status: str,
    solve_command: list[str],
    solve_return_code: int,
    artifacts: dict[str, str],
    log_summary: dict[str, Any],
    exports: list[dict[str, Any]],
    compile_command: list[str] | None,
    compile_return_code: int | None,
    compile_log_summary: dict[str, Any] | None,
    export_command: list[str] | None,
    export_return_code: int | None,
    missing: list[str],
) -> Path:
    manifest_path = output_dir / "comsol_result_manifest.json"
    manifest_artifacts = dict(artifacts)
    manifest_artifacts["result_manifest"] = str(manifest_path)
    manifest = {
        "schema_version": "comsol-result-manifest/v1",
        "status": status,
        "template_path": str(template_path),
        "solve": {
            "command": solve_command,
            "return_code": solve_return_code,
            "log_summary": log_summary,
        },
        "controlled_export": {
            "strategy": "generated_fixed_java_helper",
            "security_note": (
                "Generic COMSOL Java exports run with an isolated per-run prefsdir "
                "that grants file access to the fixed helper only."
            ),
            "compile_command": compile_command,
            "compile_return_code": compile_return_code,
            "compile_log_summary": compile_log_summary,
            "command": export_command,
            "return_code": export_return_code,
            "exports": exports,
        },
        "artifacts": manifest_artifacts,
        "missing_evidence": sorted(set(missing)),
        "guardrails": [
            "Only existing .mph templates are solved.",
            "Only the fixed ComsolResultExport.java helper generated by origin_ai_lab is executed for generic result export.",
            "The helper may export expression T only; new expressions or model edits require reviewed templates or approved model methods.",
            "LLM output is not passed through as COMSOL Java, MATLAB, LabTalk, or method code.",
        ],
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return manifest_path


def _existing_artifacts(paths: dict[str, Path]) -> dict[str, str]:
    return {key: str(path) for key, path in paths.items() if path.exists() and path.stat().st_size > 0}


def _copy_existing_files(paths: dict[Path, Path]) -> None:
    for source, destination in paths.items():
        if source.exists() and source.stat().st_size > 0:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)


def _first_existing_path(*paths: Path) -> Path | None:
    for path in paths:
        if path.exists() and path.stat().st_size > 0:
            return path
    return None


def _write_comsol_security_prefs(prefs_dir: Path) -> Path:
    prefs_dir.mkdir(parents=True, exist_ok=True)
    prefs_path = prefs_dir / "comsol.prefs"
    prefs_path.write_text("security.external.filepermission=full\n", encoding="utf-8")
    return prefs_path


def _missing_export_records(
    temperature_png: Path,
    temperature_table_csv: Path,
    max_temperature_csv: Path,
) -> list[dict[str, Any]]:
    return [
        _export_record(
            export_id="temperature_field_png",
            kind="image",
            path=temperature_png,
            expression="T",
            status_rows={},
            source="controlled_java_export",
        ),
        _export_record(
            export_id="temperature_table_csv",
            kind="csv",
            path=temperature_table_csv,
            expression="T",
            status_rows={},
            source="controlled_java_export",
        ),
        _export_record(
            export_id="max_temperature_csv",
            kind="csv",
            path=max_temperature_csv,
            expression="T",
            status_rows={},
            source="controlled_java_export",
        ),
    ]


def _export_record(
    export_id: str,
    kind: str,
    path: Path,
    expression: str,
    status_rows: dict[str, dict[str, str]],
    source: str,
) -> dict[str, Any]:
    row = status_rows.get(export_id, {})
    exists = path.exists() and path.stat().st_size > 0
    status = row.get("status") or ("created" if exists else "missing")
    if status == "created" and not exists:
        status = "missing"
    return {
        "id": export_id,
        "kind": kind,
        "path": str(path),
        "status": status,
        "created": exists,
        "expression": expression,
        "source": source,
        "message": row.get("message", ""),
    }


def _read_export_status(path: Path) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8", newline="") as file:
        rows = csv.DictReader(file, delimiter="\t")
        return {str(row.get("id") or ""): {key: str(value or "") for key, value in row.items()} for row in rows}


def _parse_max_temperature_csv(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8", newline="") as file:
        rows = csv.DictReader(file)
        for row in rows:
            metric = str(row.get("metric") or "")
            if metric != "max_temperature_C":
                continue
            try:
                return {
                    "max_temperature_C": float(str(row.get("value") or "")),
                    "max_temperature_unit": str(row.get("unit") or "degC"),
                    "max_temperature_expression": str(row.get("expression") or "T"),
                }
            except ValueError:
                return {}
    return {}


def _derive_max_temperature_from_table(table_path: Path, metric_path: Path) -> dict[str, Any]:
    if not table_path.exists():
        return {}
    with table_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.reader(file)
        header: list[str] | None = None
        temperature_index: int | None = None
        unit = "degC"
        max_value: float | None = None
        for row in reader:
            if not row:
                continue
            if row[0].startswith("%"):
                candidate = [row[0].lstrip("%").strip(), *[cell.strip() for cell in row[1:]]]
                candidate_index, candidate_unit = _temperature_column(candidate)
                if candidate_index is not None:
                    header = candidate
                    temperature_index = candidate_index
                    unit = candidate_unit
                continue
            if header is None:
                header = [cell.strip() for cell in row]
                temperature_index, unit = _temperature_column(header)
                continue
            if temperature_index is None or temperature_index >= len(row):
                continue
            try:
                value = float(row[temperature_index])
            except ValueError:
                continue
            max_value = value if max_value is None else max(max_value, value)
    if max_value is None:
        return {}
    max_temperature_c = max_value - 273.15 if unit.lower() in {"k", "kelvin"} else max_value
    with metric_path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["metric", "value", "unit", "expression", "source"])
        writer.writerow(["max_temperature_C", max_temperature_c, "degC", "T", str(table_path)])
    return {
        "max_temperature_C": max_temperature_c,
        "max_temperature_unit": "degC",
        "max_temperature_expression": "T",
        "max_temperature_source": "temperature_table_csv",
    }


def _temperature_column(header: list[str]) -> tuple[int | None, str]:
    for index, cell in enumerate(header):
        normalized = cell.strip().lower()
        if normalized == "t" or normalized.startswith("t ") or "temperature" in normalized:
            return index, _unit_from_header(cell)
    return None, "degC"


def _unit_from_header(cell: str) -> str:
    begin = cell.find("(")
    end = cell.find(")", begin + 1)
    if begin >= 0 and end > begin:
        return cell[begin + 1 : end].strip() or "degC"
    return "degC"


def _java_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n")
    return f'"{escaped}"'


def _write_process_log(path: Path, stdout: str | None, stderr: str | None) -> None:
    text = "\n".join(item.strip() for item in (stdout or "", stderr or "") if item and item.strip())
    path.write_text((text + "\n") if text else "", encoding="utf-8")


def _read_text_lossy(path: Path) -> str:
    if not path.exists():
        return ""
    for encoding in ("utf-8", "gb18030", "utf-16"):
        try:
            return path.read_text(encoding=encoding)
        except UnicodeError:
            continue
    return path.read_bytes().decode("utf-8", errors="replace")


def _log_indicates_success(log_text: str) -> bool:
    return parse_comsol_solver_log(log_text).completed


def _summarize_log(log_text: str) -> dict[str, Any]:
    return parse_comsol_solver_log(log_text).to_dict()
